[2024-04-04T12:04:03.392+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_airflow_dag.get_datetime scheduled__2024-04-04T10:03:00+00:00 [queued]>
[2024-04-04T12:04:03.395+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_airflow_dag.get_datetime scheduled__2024-04-04T10:03:00+00:00 [queued]>
[2024-04-04T12:04:03.395+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-04T12:04:03.399+0200] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_datetime> on 2024-04-04 10:03:00+00:00
[2024-04-04T12:04:03.402+0200] {standard_task_runner.py:57} INFO - Started process 86416 to run task
[2024-04-04T12:04:03.405+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'first_airflow_dag', 'get_datetime', 'scheduled__2024-04-04T10:03:00+00:00', '--job-id', '1701', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/var/folders/4w/73_t653s0rz1z847_g217g2h0000gn/T/tmp6oyq1xda']
[2024-04-04T12:04:03.406+0200] {standard_task_runner.py:85} INFO - Job 1701: Subtask get_datetime
[2024-04-05T00:12:55.470+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 86416. PIDs of all processes in the group: [86416]
[2024-04-05T00:12:55.471+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 86416
[2024-04-05T00:12:55.479+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=86416, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='12:04:03') (86416) terminated with exit code Negsignal.SIGTERM
[2024-04-05T00:12:58.414+0200] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: first_airflow_dag.get_datetime scheduled__2024-04-04T10:03:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-04-05T00:12:58.414+0200] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: first_airflow_dag.get_datetime scheduled__2024-04-04T10:03:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-04-05T00:12:58.416+0200] {local_task_job_runner.py:154} INFO - Task is not able to be run
